### ISSUE TITLE
Output Data

### ISSUE THREAD

**Issue by r-barnes** [eqasim-org/ile-de-france#14]
I note that the paper says

> We do not provide the output data of the pipeline

I wanted to note here that having a cache of the input and output data available would be very useful to me. (I work on routing algorithms and use simulated traffic data as test inputs.) The [Open Berlin Scenario](https://github.com/matsim-scenarios/matsim-berlin) and the [Chile Scenario](https://www.matsim.org/gallery/santiago) both have caches of this data. It would be great if your data were also available for easy use.

**Comment by balacmi** [comment]
Hi Richard,

You raise an interesting point. There are multiple issues with cached data. First, that this data depends on the version of the pipeline and raw data collected, which can be overcome by always having the latest version uploaded. Second, that we would need to have a server where this data is stored, which at the moment we do not have.
I understand your problem here, as you do not want to have to go through the process of building the scenario and running simulations yourself, but would just like to use the output. We can see what we can do about this in the future and if we can provide small simulation samples available for download. Do you have any specific requirements for the size of the sample that you need for your routing algorithms?

**Comment by sebhoerl** [comment]
A prepared 5% data set is now available on Mendeley. The link can be found in the recent Data in Brief article:
https://www.sciencedirect.com/science/article/pii/S2352340921008970
