### ISSUE TITLE
`synthesis.population.trips` removes all "education" purpose trips

### ISSUE THREAD

**Issue by Nitnelav** [eqasim-org/ile-de-france#44]
Hi I am trying to use the  EDGT census data for the Département 44 (Loire-Atlantique).

I got everything to work (exept a few things, notably the income wich is unavailable in the EDGT) until the `population.spatial.primary.candidates` step.

What happens is that `df_persons["has_education_trip"]` (line 68) is empty... and that raises an error on a `pd.concat` call (line 96).

Going back a bit, the issue come from the `synthesis.population.trips`.

In my test, at the beginning of the process I have the following counts : 

```
for cat in df_trips["preceding_purpose"].cat.categories:
    print("%s : %d" % (cat, len(df_trips[df_trips["preceding_purpose"] == cat])))
```
```
education : 14
home : 35
leisure : 6
other : 7
shop : 4
work : 10
```

at the end i get : 
```
education : 0
home : 75
leisure : 52
other : 8
shop : 4
work : 35
```

I know you don't have the data so you won't be able to just fix it, but could you explain what this process does ?
How do you think I should proceed, enforce at least 1 education purpose make it through the process ? or handle the case of `df_persons["has_education_trip"]` being empty ?

**Comment by sebhoerl** [comment]
Hi, for the process have a look at the [paper](https://www.researchgate.net/publication/341131284_Reproducible_scenarios_for_agent-based_transport_simulation_A_case_study_for_Paris_and_Ile-de-France), section 3.2.5 on page 13.

What do you mean with "before" and "after" the process? You mean after including EDGT? I think in at least one zone you have nobody with an education trip and this messes up the code. Might indeed be a special case that needs a special fix (probably just skipping this part if there are no education trips), but probably may also be good to check that you not filter out all education trips or something like this during the process. 

I wanted to contact you in any case, because I saw your message on Slack about the EDGT. I'll probably get access to the EDGT for Lyon next week, so I think it's worth having a call. I'll text you on Slack.

**Comment by sebhoerl** [comment]
Ah, and I think I misread the question. The problem is actually `synthesis.population.trips`, my bad. Let's discuss this in a call.

**Comment by sebhoerl** [comment]
Most likely the `pd.merge` is the cause. Have a look what happens before and after. Probably there are some `hts_id` in the matched population that don't exist in the HTS (anymore?) for some reason.

**Comment by Nitnelav** [comment]
I found the problem, it was a dumb one. `df_trips["destination_departement_id]` was accidently allmost allways outside of the requested departement (44). that left only a few trips, with a very small part of them having an 'education' purpose.
